# Generated by Django 3.2.15 on 2022-09-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(default='', max_length=70)),
                ('username', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('mobilenumber', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=50)),
                ('confirmpassword', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
