# Generated by Django 3.2.15 on 2022-10-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(default='', max_length=70)),
                ('username', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('mobilenumber', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'librarydb',
            },
        ),
    ]
