# Generated by Django 3.2.15 on 2022-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='username',
        ),
        migrations.RemoveField(
            model_name='loginmodel',
            name='usertype',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='confirmpassword',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mobilenumber',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='usertype',
            field=models.CharField(default='', max_length=70),
        ),
    ]
