# Generated by Django 3.2.15 on 2022-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='adminORuser',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10),
        ),
    ]
