# Generated by Django 3.2.15 on 2022-09-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0003_adminmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='Newuser',
        ),
        migrations.DeleteModel(
            name='AdminModel',
        ),
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.AlterModelTable(
            name='newuser',
            table='Newuser',
        ),
    ]
