# Generated by Django 3.2.15 on 2022-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0004_auto_20220918_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
