# Generated by Django 3.2.15 on 2022-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0007_adduser_cartbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='user',
            field=models.BooleanField(default=False, verbose_name='Is user'),
        ),
        migrations.AlterField(
            model_name='book',
            name='enterId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartbooks',
            name='enterId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
