# Generated by Django 3.2.15 on 2022-10-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0009_auto_20221005_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
